#!/usr/bin/env bash
# Script qui ping une adresse IP passée en argument (5 fois)

# vérifie si aucun arg a été donné 
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
    # sort avec un code d'erreur
fi

ping -c 5 "$1"
