#!/usr/bin/env bash
# Script qui modifie le fichier /etc/hosts pour changer la résolution de localhost et facebook.com
sudo tee /etc/hosts > /dev/null <<EOF
127.0.0.2 localhost
8.8.8.8 facebook.com
EOF
